name: flutter_ffmpeg_example
description: Demonstrates how to use the flutter_ffmpeg plugin.
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.68.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  path_provider:
  flutter_ffmpeg:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
