name: flutter_ffmpeg_example
description: Demonstrates how to use the flutter_ffmpeg plugin.
version: 0.3.0
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  path_provider: ^1.6.16
  path: ^1.7.0
  fluttertoast: ^7.1.1
  video_player: ^0.10.12+3
  flutter_ffmpeg: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
