name: flutter_ffmpeg
description: Flutter plugin to run FFmpeg on mobile platforms. Supports iOS and Android.
version: 0.4.0
homepage: https://github.com/tanersener/flutter-ffmpeg

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^2.0.1
  path: ^1.8.0

flutter:
  plugin:
    platforms:
      android:
        package: com.arthenica.flutter.ffmpeg
        pluginClass: FlutterFFmpegPlugin
      ios:
        pluginClass: FlutterFFmpegPlugin
